version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: glutenfree-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/app/
    depends_on:
      - php
    networks:
      - glutenfree-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: glutenfree-php
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - glutenfree-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: glutenfree_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - glutenfree-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: glutenfree-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@glutenfree.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - glutenfree-network

networks:
  glutenfree-network:
    driver: bridge

volumes:
  pg-data: